:spring_boot_version: 1.5.10.RELEASE
:jdk: https://www.oracle.com/technetwork/java/javase/downloads/index.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-gradle

== What you'll build

Simple app and then build it using Gradle.

== Prerequisites
 - {jdk}[JDK 6] or later
 - https://gradle.org/install/[Install Gradle]

== How has it been created?
 - Create directory structure `src/main/java/hello`
 - Create 2 classes

`src/main/java/hello/HelloWorld.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/hello/HelloWorld.java[]
----

`src/main/java/hello/Greeter.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/hello/Greeter.java[]
----

 - Create a very basic `build.gradle` file in the <project folder>
[source,groovy]
----
include::initial/build.gradle[]
----

 - Run `gradle tasks`, and you see new tasks added to the list -- for building the project, creating JavaDoc, and running tests --

 - Run `gradle build`, and you see that task compiles, tests, and assembles the code into a JAR file.
    ** Take a look in the _build_ folder
        *** _classes_
            **** The project's compiled .class files.
            **** _dependency_cache_ folder is empty because there is nothing of code now
        *** _reports_
            **** Reports produced by the build of running unit tests
        *** _libs_
            **** Assembled project libraries (usually JAR and/or WAR files)


== Declare dependencies
* Add a source for 3rd party libraries.
[source,groovy]
----
include::complete/build.gradle[tag=repositories]
----
* Add dependencies
[source,groovy]
----
include::complete/build.gradle[tag=dependencies]
----
* Add business logic, to print the current date and time.

[source,java,tabsize=2]
----
package hello;

import org.joda.time.LocalTime;

public class HelloWorld {
  public static void main(String[] args) {
    LocalTime currentTime = new LocalTime();
    System.out.println("The current local time is: " + currentTime);

    Greeter greeter = new Greeter();
    System.out.println(greeter.sayHello());
  }
}
----
* `gradle build` / `./gradlew build`
* Dependency scopes
    ** `compile`
        *** should be available during compile-tim
    ** `implementation`
        *** required for compiling the project code
        *** provided at runtime by a container running the code -- _Example:_ Java Servlet API --
    ** `testImplementation`
        *** required for compiling and running tests
        *** NOT required for building or running the project's runtime code.

== Other configurations
* Specify the name for our JAR artifact

[source,groovy]
----
include::complete/build.gradle[tag=jar]
----

== Make the code runnable
* `jar tvf build/libs/gs-gradle-0.1.0.jar` and you notice that
    ** class files are bundled up
    ** 'joda-time' is NOT included here
----
$ jar tvf build/libs/gs-gradle-0.1.0.jar
  0 Fri May 30 16:02:32 CDT 2014 META-INF/
 25 Fri May 30 16:02:32 CDT 2014 META-INF/MANIFEST.MF
  0 Fri May 30 16:02:32 CDT 2014 hello/
369 Fri May 30 16:02:32 CDT 2014 hello/Greeter.class
988 Fri May 30 16:02:32 CDT 2014 hello/HelloWorld.class
----
* `java -jar build/libs/gs-gradle-0.1.0.jar` fails because it's NOT runnable
* Make this code runnable -- via -- gradle's `application` plugin

----
apply plugin: 'application'
mainClassName = 'hello.HelloWorld'
----
* `./gradlew run` to check that it's runnable

----
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
The current local time is: 16:16:20.544
Hello world!

BUILD SUCCESSFUL

Total time: 3.798 secs
----

== Notes
* If we were building a WAR file -> we could use gradle's https://www.gradle.org/docs/current/userguide/war_plugin.html[WAR plugin]
* If you are using Spring Boot and want a runnable JAR file ->  https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-gradle[spring-boot-gradle-plugin]


== vs Maven
* Check https://spring.io/guides/gs/maven/[Building Java Projects with Maven]
